spring.application.name=devops

#Configurações do banco de dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devops_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

#Atualização automatica do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

#Mostrar as consultas SQL no console
spring.jpa.show-sql=true

#Não mostrar as formatações SQL
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

#Configurações da porta do servidor
server.port=8080
app.base-url=${APP_BASE_URL:http://localhost:${server.port}}
# Desabilita a página Whitelabel do Spring Boot para usar nossa `error.html`
server.error.whitelabel.enabled=false
#Configurações de Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
