spring.application.name=fatecads
spring.config.import=optional:file:./application-secrets.properties

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.base-url=http://localhost:8080
app.security.password-reset.expiration-minutes=30
app.security.password-reset.cooldown-seconds=60

resend.api-key=
resend.api-url=https://api.resend.com/emails
resend.from-email=onboarding@resend.dev
resend.from-name=FatecADS
